language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: SYMFONY_VERSION=3.4.*
        - php: 7.2
          env: SYMFONY_VERSION=4.3.*
        - php: 7.2
          env: SYMFONY_VERSION=4.4.*
        - php: 7.2
          env: SYMFONY_VERSION=5.0.*
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.3
          env: SYMFONY_VERSION=3.4.*
        - php: 7.3
          env: SYMFONY_VERSION=4.3.*
        - php: 7.3
          env: SYMFONY_VERSION=4.4.*
        - php: 7.3
          env: SYMFONY_VERSION=5.0.*
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.4
          env: SYMFONY_VERSION=3.4.*
        - php: 7.4
          env: SYMFONY_VERSION=4.3.*
        - php: 7.4
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4
          env: SYMFONY_VERSION=5.0.*
    allow_failures:
      - env: COMPOSER_FLAGS="--prefer-lowest"
      - env: SYMFONY_VERSION=5.0.*
before_install:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$SYMFONY_VERSION" = "5.0.*" ]; then composer remove "friendsofsymfony/oauth-server-bundle" --no-update; fi;
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
